# fly.toml app configuration file generated for activities-app on 2024-01-27T23:37:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'activities-app'
primary_region = 'cdg'

[build]
  image = 'dockerelite/activities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinaryName__CloudName="dzxmtv4jz"
  CloudinaryName__ApiKey="325962177368828"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
